#log4j配置文件位置
logging:
  config: classpath:log4j/log4j2.xml
  # 打印sql
  level:
    com.fei.springboothigh.mapper: debug

#数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
#redis配置
  redis:
    host: 192.168.31.60
    port: 6379
#rabbitmq配置
  rabbitmq:
    host: 192.168.31.60
    username: admin
    password: 123456
    port: 5672

#Mybatis配置文件
mybatis:
  mapper-locations: classpath:mapper/*.xml
