#log4j配置文件位置
logging:
  config: classpath:log4j/log4j2.xml
    # 打印sql
  level:
    com.fei.springboothigh.mapper: debug

#数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

#Mybatis配置文件
mybatis:
  mapper-locations: classpath:mapper/*.xml
